Changes to Python-ROS 2 API (#67)
* [common_robot] Add common robot node

* Allow bases to take multiple types of cores, add xyaw velocity for duration method

* Add InterbotixSlateInterface, InterbotixSlate modules

* Lint

* Don't import all xs_modules submodules

* Add aloha arm variants

* Do better executor management

* Add InterbotixRobotNode common robot class

* Add Interbotix exceptions

* Lint common robot module

* Update core to use robot wait method

* Minor improvements to Slate module

* Lint core

* Lint mobile_base module, fix minor error

* Add slate-humble workflow

* Fix attempt

* Remove slate workflow

* Add ALOHA arm mr variants

* Use node logging methods

* Lint

diff --git a/.github/workflows/xs-humble.yaml b/.github/workflows/xs-humble.yaml
--- a/.github/workflows/xs-humble.yaml
+++ b/.github/workflows/xs-humble.yaml
@@ -39,6 +39,7 @@ jobs:
         run: python3 -m pip install modern-robotics transforms3d
       - name: Prepare Workspace
         run: |
+          rm src/interbotix_ros_core/interbotix_ros_xseries/COLCON_IGNORE || echo "File not found"
           rm src/interbotix_ros_toolboxes/interbotix_perception_toolbox/COLCON_IGNORE
           rm src/interbotix_ros_toolboxes/interbotix_common_toolbox/interbotix_moveit_interface/COLCON_IGNORE
           rm src/interbotix_ros_toolboxes/interbotix_common_toolbox/interbotix_moveit_interface_msgs/COLCON_IGNORE
